(() => {
 'use strict';const C=window.TripCore;
 const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};
 window.TripTiming={prepare(config){
  const key=`kelione2026.${config.id}.timing.v1`;let state={days:{},legs:{}},broken=false,anchor=null,resumeStale=false;
  const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}};
  const custom=()=>read(`kelione2026.${config.id}.plan.v1`)?.items||[];
  try{state=JSON.parse(localStorage.getItem(key)||'null')||state;C.timingValid(state,config,new Set([...config.days.flatMap(d=>d.stops.map(s=>s.id)),...custom().map(x=>x.id)]))}catch{broken=true;state={days:{},legs:{}}}
  const panel=el('section');panel.className='timing-panel';panel.setAttribute('aria-label','Grįžimo laikas');document.querySelector('.mode-bar').after(panel);
  const heading=el('h2','Dienos planas'),summary=el('p'),source=el('p','Planiniai įverčiai, be gyvo eismo duomenų. Atsarga skaičiuojama vieną kartą.'),message=el('p');summary.setAttribute('role','status');message.setAttribute('role','status');source.className='timing-source';
  const actions=el('div');actions.className='timing-actions';const resume=el('button','Tęsti nuo čia'),reset=el('button','Dienos planas'),settings=el('button','Laiko nustatymai');for(const b of [resume,reset,settings])b.type='button';actions.append(resume,reset,settings);
  const details=el('details'),detailTitle=el('summary','Atkarpos ir trukmės'),body=el('div');details.append(detailTitle,body);panel.append(heading,summary,source,actions,message,details);
  function save(next){if(broken){message.textContent='Laiko duomenys neįskaitomi. Pirmiausia eksportuokite atsarginę kopiją.';return false}try{localStorage.setItem(key,JSON.stringify(next));state=next;return true}catch{message.textContent='Išsaugoti nepavyko; ankstesni laikai nepakeisti.';return false}}
  const dayNow=()=>config.days.find(d=>d.id===window.TripPlanner.activeDay())||config.days[0];
  function getStops(day){const originals=new Map(day.stops.map(s=>[s.id,s])),items=new Map(custom().map(x=>[x.id,x]));return [...document.getElementById(day.id).querySelectorAll('.step')].map(node=>{const id=node.dataset.stopId,item=items.get(id);return originals.get(id)||item&&{id,title:item.name,destination:`${item.lat},${item.lon}`,mode:'driving',visitMinutes:item.minutes,terminal:false}}).filter(Boolean)}
  function build(){const day=dayNow(),settings={...day.timing,...state.days[day.id]},all=getStops(day),skipped=new Set(read(`kelione2026.${config.id}.skipped.v1`)||[]),visited=new Set(read(config.storageKey)||[]);let start=day.start,startMinutes=C.clock(settings.departure),stay=0,stops=all;
   if(anchor){const i=all.findIndex(s=>s.id===anchor.id);if(anchor.id&&i<0){resumeStale=true;anchor=null}else{start=anchor.destination;startMinutes=anchor.minutes;stay=anchor.stay;stops=anchor.id?all.slice(i+1):all;stops=stops.filter(s=>!visited.has(s.id))}}
   stops=stops.filter(s=>!s.terminal&&!skipped.has(s.id)).map(s=>({...s,visitMinutes:state.days[day.id]?.visits?.[s.id]??s.visitMinutes}));
   const legs=Object.assign({},...config.days.map(d=>d.legs),day.legs,state.legs);
   const result=C.calculate({start,startMinutes,stops,end:day.end,endMode:day.stops.at(-1).mode,legs,breakMinutes:settings.breakMinutes,stayMinutes:stay,departureMinutes:C.clock(settings.departure),returnMinutes:settings.returnBy?C.clock(settings.returnBy):null,bufferMinutes:settings.bufferMinutes});return {day,settings,result,all,stops};
  }
  function render(){const {day,settings,result,all}=build();heading.textContent=anchor?`Likusi diena · nuo ${C.format(anchor.minutes)}`:'Dienos planas';reset.hidden=!anchor&&!resumeStale;
   source.textContent=`Išvykimas ${settings.departure} · grįžti iki ${settings.returnBy||'nenustatyta'} · atsarga ${settings.bufferMinutes} min. Planiniai įverčiai be gyvo eismo. Kortelėse – pirminio plano laikai.`;
   panel.dataset.status=resumeStale?'incomplete':result.status;
   if(broken)summary.textContent='Išsaugoti laikai neįskaitomi. Skaičiavimas sustabdytas.';
   else if(resumeStale)summary.textContent='Pasikeitė progresas arba planas. Iš naujo pasirinkite „Tęsti nuo čia“.';
   else if(result.finish===null)summary.textContent=`Grįžimo laikas nevisiškai apskaičiuotas: trūksta ${result.missing.length} trukmės įverčio (-ių). Žinomų trukmių suma: ${Math.round(result.knownMinutes)} min.`;
   else{let text=`Planinis grįžimas ${C.format(result.finish)}.`;if(result.status==='no-deadline')text+=' Grįžimo terminas nenustatytas.';else if(result.status==='late')text+=` Terminas viršijamas ${Math.ceil(-result.margin)} min.`;else if(result.status==='low-buffer')text+=` Iki termino lieka ${Math.floor(result.margin)} min.; nustatyta atsarga nebeišlaikoma.`;else text+=` Iki termino lieka ${Math.floor(result.margin)} min. Telpate su atsarga.`;summary.textContent=text}
   body.replaceChildren();const names=new Map(all.map(s=>[s.destination,s.title]));names.set(day.start,'Dienos pradžia');names.set(day.end,'Dienos pabaiga');const used=new Set();
   for(const segment of result.segments){if(segment.from===segment.to||used.has(segment.key))continue;used.add(segment.key);const row=el('label',`${segment.mode==='walking'?'Ėjimas':'Kelias'}: ${names.get(segment.from)||segment.from} → ${names.get(segment.to)||segment.to}`),input=el('input');input.type='number';input.min='0';input.max='2880';input.step='1';input.value=segment.minutes??'';input.placeholder='Trūksta min.';input.setAttribute('aria-label',`${row.textContent} (min.)`);row.append(input,el('small',segment.source==='manual'?'Jūsų įvertis, min.':segment.minutes!==null?'Pirminio plano įvertis, min.':'Nežinoma trukmė. Įrašykite įvertį minutėmis.'));body.append(row);
    input.onchange=()=>{if(!input.reportValidity())return;const next=JSON.parse(JSON.stringify(state));if(input.value==='')delete next.legs[segment.key];else next.legs[segment.key]={minutes:Number(input.value),source:'manual'};if(save(next))render()};
   }
   for(const missing of result.missing.filter(x=>x.type==='visit'))body.append(el('p',`Trūksta lankymo trukmės: ${missing.title}. Įrašykite „Laiko nustatymuose“.`));
   detailTitle.textContent=`Atkarpos ir trukmės · ${result.missing.length?'trūksta įverčių':'įverčiai užpildyti'}`;
  }
  function dialog(title){const d=el('dialog');d.className='place-dialog';const form=el('form');form.append(el('h2',title));d.append(form);document.body.append(d);d.addEventListener('close',()=>d.remove());const field=(label,type,value)=>{const l=el('label',label),i=el('input');i.type=type;i.value=value??'';i.setAttribute('aria-label',label);l.append(i);form.append(l);return i};const finish=handler=>{const ok=el('button','Išsaugoti'),cancel=el('button','Atšaukti');ok.type='submit';cancel.type='button';cancel.onclick=()=>d.close();form.append(ok,cancel);form.onsubmit=e=>{e.preventDefault();if(form.reportValidity()&&handler())d.close()};d.showModal()};return {d,form,field,finish}}
  settings.onclick=()=>{const {day,settings,all}=build(),ui=dialog('Laiko nustatymai');const departure=ui.field('Išvykimas','time',settings.departure),deadline=ui.field('Grįžti iki (neprivaloma)','time',settings.returnBy);departure.required=true;const buffer=ui.field('Atsarga, min.','number',settings.bufferMinutes),pause=ui.field('Papildomos pertraukos, min.','number',settings.breakMinutes);for(const i of [buffer,pause]){i.required=true;i.min='0';i.max='2880';i.step='1'}ui.form.append(el('p','Į lankymo trukmę įtraukite laiką objekte. Jau įtrauktų pietų ar pasivaikščiojimų pakartotinai nepridėkite. Tęsiant dieną pertraukų lauke palikite tik dar likusias pertraukas.'));
   const visits=all.filter(s=>!s.terminal).map(s=>{const i=ui.field(s.title+' – lankymas, min.','number',settings.visits?.[s.id]??s.visitMinutes);i.min='0';i.max='2880';i.step='1';return [s.id,i]});ui.finish(()=>{const next=JSON.parse(JSON.stringify(state)),v={};for(const [id,i] of visits)if(i.value!=='')v[id]=Number(i.value);next.days[day.id]={departure:departure.value,returnBy:deadline.value||null,bufferMinutes:Number(buffer.value),breakMinutes:Number(pause.value),visits:v};if(!save(next))return false;anchor=null;resumeStale=false;render();return true})};
  resume.onclick=()=>{const {day,all}=build(),ui=dialog('Tęsti nuo čia'),label=el('label','Dabartinė vieta'),select=el('select');select.setAttribute('aria-label','Dabartinė vieta');const initial=el('option','Dienos pradžia');initial.value='';select.append(initial);for(const s of all){const o=el('option',s.title);o.value=s.id;select.append(o)}label.append(select);ui.form.append(label);const stay=ui.field('Dar būsiu čia, min. (0 – išvykstu dabar)','number',0);stay.min='0';stay.max='2880';stay.required=true;stay.step='1';ui.form.append(el('p','Skaičiuojama nuo pasirinktos vietos dabartiniu kelionės laiku. Ankstesnės ir jau aplankytos vietos neįtraukiamos. Tai nėra GPS sekimas.'));
   ui.finish(()=>{const parts=new Intl.DateTimeFormat('en-GB',{timeZone:config.timeZone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const part=t=>parts.find(x=>x.type===t).value;const current=all.find(s=>s.id===select.value);anchor={id:select.value,destination:current?.destination||day.start,minutes:Number(part('hour'))*60+Number(part('minute')),stay:Number(stay.value)};resumeStale=false;render();return true})};
  reset.onclick=()=>{anchor=null;resumeStale=false;render()};
  window.addEventListener('trip-day-changed',()=>{anchor=null;resumeStale=false;render()});
  for(const event of ['trip-plan-changed','trip-status-changed'])window.addEventListener(event,()=>{if(anchor)resumeStale=true;render()});
  render();
 }};
})();
