const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{
 const fs=require('node:fs'),path=require('node:path'),http=require('node:http');
 const root=path.resolve(__dirname,'..');
 const server=http.createServer((req,res)=>{const relative=new URL(req.url,'http://localhost').pathname.replace(/^\/kelione-2026\//,'');const file=path.resolve(root,relative||'index.html');if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);res.end();return}const ext=path.extname(file);res.setHeader('Content-Type',({'.js':'application/javascript','.json':'application/json','.html':'text/html','.css':'text/css'})[ext]||'application/octet-stream');res.end(data)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));server.unref();
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.TEST_URL||`http://127.0.0.1:${server.address().port}/kelione-2026/`;
 await page.goto(base+'?trip=alanya-2026');await page.locator('.day:visible .visit-btn').first().waitFor();
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.locator('.day:visible .visit-btn').first().waitFor();
 assert.equal(await page.locator('.day:visible').count(),1);
 await page.getByRole('button',{name:'Planuoti',exact:true}).click();
 await page.getByRole('button',{name:'+ Pridėti vietą',exact:true}).click();
 await page.getByLabel('Pavadinimas',{exact:true}).fill('Bandomoji vieta');
 await page.getByLabel('Platuma (įtraukiant į dieną)',{exact:true}).fill('36.55');
 await page.getByLabel('Ilguma (įtraukiant į dieną)',{exact:true}).fill('32.1');
 await page.getByLabel('Kur išsaugoti',{exact:true}).selectOption('a1');
 await Promise.all([page.waitForEvent('load'),page.getByRole('button',{name:'Išsaugoti',exact:true}).click()]);
 await page.locator('[data-custom]').waitFor();assert.equal(await page.locator('[data-custom]').count(),1);
 const custom=page.locator('[data-custom]');await custom.locator('.visit-btn').click();assert.equal(await custom.getAttribute('class'),'step visited');
 await custom.getByRole('button',{name:'↓ Žemyn',exact:true}).click();
 await page.reload();await page.locator('[data-custom].visited').waitFor();
 await page.getByRole('button',{name:'Keliauti',exact:true}).click();await page.locator('.day:visible .skip-btn').first().click();
 assert.equal(await page.locator('.day:visible .skipped').count(),1);
 await page.getByLabel('Pasirinkta diena',{exact:true}).selectOption('a2');assert.equal(await page.locator('.day:visible').getAttribute('id'),'a2');
 await page.evaluate(()=>window.scrollTo(0,0));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile layout overflows');
 if(process.env.SCREENSHOT_PATH)await page.screenshot({path:process.env.SCREENSHOT_PATH,fullPage:true});
 await context.setOffline(true);await page.reload();await page.locator('.day:visible .visit-btn').first().waitFor();assert.equal(await page.locator('.day:visible').getAttribute('id'),'a2');
 await page.getByLabel('Pasirinkta diena',{exact:true}).selectOption('a1');assert.equal(await page.locator('[data-custom].visited').count(),1);
 await page.getByRole('button',{name:'Planuoti',exact:true}).click();await page.getByRole('button',{name:'+ Pridėti vietą',exact:true}).click();await page.getByLabel('Pavadinimas',{exact:true}).fill('Offline norima vieta');
 await Promise.all([page.waitForEvent('load'),page.getByRole('button',{name:'Išsaugoti',exact:true}).click()]);await page.getByText('Offline norima vieta',{exact:true}).waitFor();
 await context.setOffline(false);await page.locator('#tripSelect').selectOption('europe-2026');await page.waitForURL('**trip=europe-2026');await page.locator('.day:visible .visit-btn').first().waitFor();assert.equal(await page.locator('.step').count(),65);assert.equal(await page.locator('.step.visited').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS Chromium mobile 390px: add/edit flow, reorder/persist, skip, day switch, no overflow, offline reload/add wishlist, trip isolation; no JS errors.');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
